export const toolsTechImage = {
    html5: "html.svg",
    css: "css.svg",
    javascript:"javascript.svg",
    php: "php.svg",
    c: "c.svg",
    reactjs: "react.svg",
    vue: "vue.svg",
    python: "python.svg",
    bash: "bash.svg",
    ansible: "ansible.svg",
    css3: "css.svg",
    cpp: "cpp.svg",
    bootstrap: "bootstrap.svg",
    djangorestframework: "djangorest.svg",
    docker: "docker.svg",
    expressjs: "express.svg",
    flask: "flask.svg",
    figma: "figma.svg",
    mongodb: "mongodb.svg",
    mysql: "mysql.svg",
    laravel: "laravel.svg",
    html: "html.svg",
    nginx: "nginx.svg",
    nodejs: "node.svg",
    postgresql: "postgresql.svg",
    python: "python.svg",
    redis: "redis.svg",
    typescript: "typescript.svg",
    django: "django.svg",
    webrtc: "webrtc.svg",
    websocket: "websocket.svg",
    ubuntu: "ubuntu.svg",
    ejs: "ejs.svg",
    puppet: "puppet.svg",
    ruby: "ruby.svg"
}
